### ISSUE TITLE
What is the reason of this Class?

### ISSUE THREAD

**Issue by LuisErnestoZamb** [wahidahossain/API#1]
Or how/why this class appeared?

Please, remove those part of your code that you are not using or do the project from the scratch. I am extending the deadline of Lab 1.

https://github.com/wahidahossain/API/blob/5e412a9a27c0da856280b76da0c8f51021b43556/s3bucket.cs#L9

**Comment by wahidahossain** [comment]
I am getting my bucket list (bucket name and date) using GetBucketList() function and making instances in s3bucket.cs (instances are BucketName and CreationDate)
